apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: password-generator
data:
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector-deployment-opentelemetry-collector.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_SERVICE_NAME: "python-fastapi-automatic-poetry-uvicorn"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_PYTHON_LOG_LEVEL: "info"
  OTEL_SERVICE_NAMESPACE: "production"

  SERVICE_OWNER_NAME: "gabrielcarvalho"
  SERVICE_OWNER_CONTACT: "gabrielcarvalho.workk@gmail.com"

  SERVICE_VERSION: "0.2.14"
  COMMIT_HASH: "175d6afd713dd8c0aa9eaa39200cbade1372c447"
  COMMIT_BRANCH: "main"
  DEPLOYMENT_USER: "gabszs"
  DEPLOYMENT_TRIGGER: "push"
