apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: password-generator
data:
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://collector.gabrielcarvalho.dev"
  OTEL_EXPORTER_OTLP_INSECURE: "false"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_SERVICE_NAME: "python-fastapi-automatic-poetry-uvicorn"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_PYTHON_LOG_LEVEL: "info"

  SERVICE_VERSION: "0.2.12"
  COMMIT_HASH: "a134c8ada4b4b3d7da25648b250df45774f508fa"
  COMMIT_BRANCH: "main"
  DEPLOYMENT_USER: "gabszs"
  DEPLOYMENT_TRIGGER: "push"
