apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: password-generator
data:
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://collector.gabrielcarvalho.dev"
  OTEL_EXPORTER_OTLP_INSECURE: "false"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_SERVICE_NAME: "pve-prod-password-generetor-api"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "otlp"
  SERVICE_VERSION: "0.2.10"
  COMMIT_HASH: "418d93ac8e4fe4e73abd0ae0473508f12b8f64e9"
  COMMIT_BRANCH: "main"
  DEPLOYMENT_USER: "gabszs"
  DEPLOYMENT_TRIGGER: "push"
  OTEL_PYTHON_LOG_LEVEL: "info"

