apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: password-generator
data:
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://collector.gabrielcarvalho.dev"
  OTEL_EXPORTER_OTLP_INSECURE: "false"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_SERVICE_NAME: "pve-prod-password-generetor-api"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_PYTHON_LOG_LEVEL: "info"

  SERVICE_VERSION: "0.2.11"
  COMMIT_HASH: "356dba8161f4500f182f8491795de545c1f1674c"
  COMMIT_BRANCH: "main"
  DEPLOYMENT_USER: "gabszs"
  DEPLOYMENT_TRIGGER: "push"
