apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  namespace: password-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordservice
  template:
    metadata:
      labels:
        app: passwordservice
    spec:
      containers:
      - name: passwordservice
        image: gabzsz/password-generator:6d168f6
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: config-map
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
