apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  namespace: password-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordservice
  template:
    metadata:
      labels:
        app: passwordservice
    spec:
      containers:
      - name: passwordservice
        image: gabzsz/password-generator:ef48e1e
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: config-map
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-multiple-workers
  namespace: password-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordservice-multiple-workers
  template:
    metadata:
      labels:
        app: passwordservice-multiple-workers
    spec:
      containers:
      - name: passwordservice-multiple-workers
        image: gabzsz/password-generator:multiple-workers
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: config-map
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
