apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  namespace: password-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordservice
  template:
    metadata:
      labels:
        app: passwordservice
    spec:
      containers:
      - name: passwordservice
        image: gabzsz/password-generator:0e3b9c4
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: config-map
        env:
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.namespace=$(OTEL_SERVICE_NAMESPACE),k8s.pod.ip=$(K8S_POD_IP),service.environment=$(OTEL_SERVICE_NAMESPACE),service.version=$(SERVICE_VERSION),service.build.git_hash=$(COMMIT_HASH),service.owner.name=$(SERVICE_OWNER_NAME),service.owner.contact=$(SERVICE_OWNER_CONTACT),service.build.git_branch=$(COMMIT_BRANCH),service.build.deployment.user=$(DEPLOYMENT_USER),service.build.deployment.trigger=$(DEPLOYMENT_TRIGGER)"     
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
