apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: password-generator-scaledobject
  namespace: password-generator
spec:
  scaleTargetRef:
    kind: Deployment
    name: password-generator-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"

    - type: memory
      metricType: Utilization
      metadata:
        value: "75"
#     # # Escalonamento baseado em cron
#     # - type: cron
#     #   metadata:
#     #     timezone: "America/Sao_Paulo"
#     #     start: "25 21 * * *"   # Inicia às 21:25
#     #     end: "35 21 * * *"     # Termina às 21:28
#     #     desiredReplicas: "5"   # Número de réplicas durante o cron
