apiVersion: v1
kind: Service
metadata:
  name: password-generator-svc
  namespace: password-generator
spec:
  type: ClusterIP
  selector:
    app: passwordservice
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: password-generator-multiple-workers-svc
  namespace: password-generator
spec:
  type: ClusterIP
  selector:
    app: passwordservice-multiple-workers
  ports:
  - port: 80
    targetPort: 80
